"""Replace living_space_min/max with single living_space

Revision ID: 9c6b5de1d93c
Revises: 00242a7ac65a
Create Date: 2026-04-29 12:13:34.167156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c6b5de1d93c'
down_revision = '00242a7ac65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('living_space', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('living_space_max')
        batch_op.drop_column('living_space_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('living_space_min', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('living_space_max', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('living_space')

    # ### end Alembic commands ###
