"""Add FK from preferences.client_id to clients.id and ORM relationship

Revision ID: 00242a7ac65a
Revises: 5dfc0bc13a3a
Create Date: 2026-04-29 10:51:05.131880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00242a7ac65a'
down_revision = '5dfc0bc13a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
