"""Clean initial migration with all models

Revision ID: 5dfc0bc13a3a
Revises: 
Create Date: 2026-04-29 09:55:57.244572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dfc0bc13a3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('offer_type')
    with op.batch_alter_table('offer_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('offers_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('type')
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('property_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('accepts_offers', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('property_status', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('accepts_offers')
        batch_op.drop_column('status')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key(batch_op.f('offers_ibfk_3'), 'agents', ['agent_id'], ['id'])

    with op.batch_alter_table('offer_status', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    op.create_table('offer_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('offer_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
